config/routes.rb
# For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

Rails.application.routes.draw do
  root 'pages#home'
  get 'about', to: 'pages#about'
  get 'privacy', to: 'pages#privacy'
  get 'process', to: 'pages#process'

  LINKS.each do |path, url|
    get path.to_s.gsub("_","/"), to: redirect(url)
  end

  REDIRECTS.each do |from, to|
    get from, to: redirect(to)
    get "#{from}/*video", to: redirect("#{to}/%{video}"), constraints: { video: /.*/ }
  end

  resources :channels, only: [:index, :new, :create]
  resources :videos, only: [:index, :new, :create]

  resources :channels, path: '/', except: [:index, :new, :create] do
    member do
      get :sync, :edit # fixes the video path taking over
    end
    resources :videos, path: '/', except: [:index, :new, :create] do
      member do
        get :sync
      end
    end
  end
end

app/models/channel.rb
class Channel < ApplicationRecord
  include Discard::Model
  extend FriendlyId

  after_initialize :set_slug

  has_many :features, dependent: :destroy

  has_many :videos, dependent: :destroy
  has_many :video_sources, through: :videos, source: :sources

  has_many :sources, class_name: "::ChannelSource", dependent: :destroy
  has_one :peertube, class_name: "::ChannelSource::Peertube"
  has_one :youtube, class_name: "::ChannelSource::Youtube"

  has_many :socials, class_name: "::ChannelSocial", dependent: :destroy
  has_many :supports, class_name: "::ChannelSupport", dependent: :destroy

  validates :name, :slug, presence: true, uniqueness: true

  scope :order_by_created, -> { order(created_at: :desc) }
  scope :order_by_slug, -> { order(slug: :asc) }
  scope :order_by_oldest, -> { order(updated_at: :asc) }
  scope :order_by_latest, -> { order(published_at: :desc) }
  scope :random, -> { order("RANDOM()") }
  scope :needs_update, -> { where(updated_at: ..1.day.ago) }
  scope :needs_sync, -> { joins(:sources).merge(ChannelSource.needs_sync).order("channel_sources.synced_at desc") }
  scope :needs_videos, -> { includes(:videos).where(videos: { channel_id: nil} ) }

  friendly_id :name

  def to_s
    name
  end

  def refresh!
    youtube.refresh!

    self.touch
  end

  def sync!
    youtube.sync!

    self.touch
  end

  def normalize_friendly_id(string)
    super.gsub("-", "")
  end
end

app/controllers/channels_controller.rb
class ChannelsController < ApplicationController
  before_action :set_channel, only: [:edit, :sync, :update, :destroy]
  before_action :set_channel_and_videos, only: [:show]
  before_action :not_production, only: [:new, :create, :edit, :update, :destroy]

  # GET /channels
  # GET /channels.json
  def index
    @q = Channel.kept.includes(:sources).order_by_slug.ransack(params[:q])
    @channels = @q.result(distinct: true)
    @pagy, @channels = pagy(@channels, items: params[:items])
  end

  # GET /channels/1
  # GET /channels/1.json
  def show
  end

  # GET /channels/new
  def new
    @channel = Channel.new
  end

  # GET /channels/1/edit
  def edit
  end

  # GET /channels/1/sync
  def sync
    @channel.sync!

    redirect_to channel_path(@channel)
  end

  # POST /channels
  # POST /channels.json
  def create
    @channel = Channel.new(channel_params)

    respond_to do |format|
      if @channel.save
        format.html { redirect_to @channel, notice: 'Channel was successfully created.' }
        format.json { render :show, status: :created, location: @channel }
      else
        format.html { render :new }
        format.json { render json: @channel.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /channels/1
  # PATCH/PUT /channels/1.json
  def update
    respond_to do |format|
      if @channel.update(channel_params)
        format.html { redirect_to @channel, notice: 'Channel was successfully updated.' }
        format.json { render :show, status: :ok, location: @channel }
      else
        format.html { render :edit }
        format.json { render json: @channel.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /channels/1
  # DELETE /channels/1.json
  def destroy
    @channel.destroy
    respond_to do |format|
      format.html { redirect_to channels_url, notice: 'Channel was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_channel
      @channel = Channel.kept.includes(:sources).friendly.find(params[:id])
    end

    def set_channel_and_videos
      @channel = Channel.kept.includes(:sources, :supports, :socials, :videos).friendly.find(params[:id])
      @videos = @channel.videos.kept.includes(:channel, :sources).published.latest
      @sources = @channel.sources.order_by_type
      @socials = @channel.socials.order_by_type
      @supports = @channel.supports.order_by_type
      @pagy, @videos = pagy(@videos, items: params[:items])
    end

    # Only allow a list of trusted parameters through.
    def channel_params
      params.require(:channel).permit(:name, :slug, :description, :image)
    end
end

app/helpers/channels_helper.rb
module ChannelsHelper
end

app/views/channels/_channel.html.erb
<div class="col mb-4">
  <div class="card card-block">
    <%= link_to(
          image_tag(channel.image, class: "card-img-top", style: "min-height: 300px", alt: channel.name),
          channel) %>
    <div class="card-body p-2">
      <h5 class="card-title text-truncate mb-0"><%= link_to channel.name, channel, title: channel.name %></h5>
      <p class="card-text mb-0" style="height: 72px">
        <small>
          <abbr title="<%= channel.description %>">
            <%= truncate(channel.description, length: 90) %>&nbsp;
          </abbr>
        </small>
      </p>
      <div class="btn-group btn-group-sm btn-block mt-2">
        <% channel.sources.each do |source| %>
          <%= link_to I18n.t(source.kind), source.url, class: "btn btn-#{ source.kind }", target: :blank %>
        <% end %>
      </div>
    </div>
    <% if Rails.env.development? %>
      <div class="card-footer p-2">
        <div class="btn-group btn-group-sm btn-block">
          <%= link_to "Edit", edit_channel_path(channel), class: "btn btn-light btn-outline-dark" %>
          <%= link_to 'Destroy', channel, method: :delete, class: "btn btn-outline-danger", data: { confirm: 'Are you sure?' } %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/channels/_form.html.erb
<%= form_with(model: channel, local: true) do |form| %>
  <% if channel.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(channel.errors.count, "error") %> prohibited this channel from being saved:</h2>

      <ul>
        <% channel.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :slug %>
    <%= form.text_field :slug %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="field">
    <%= form.label :image %>
    <%= form.text_field :image %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/channels/edit.html.erb
<h1>Editing Channel</h1>

<%= render 'form', channel: @channel %>

<%= link_to 'Show', @channel %> |
<%= link_to 'Back', channels_path %>

app/views/channels/index.html.erb
<div class="container-fluid">
  <div class="row my-2">
    <div class="col">
      <div class="d-block d-md-flex justify-content-between">
        <h1 class="h2 mb-2 mr-auto">
          <%= link_to I18n.t(:channels), channels_path %>
        </h1>

        <div class="mb-2 mr-0 mr-md-2">
          <%= search_form_for @q, wrapper: :inline_form do |f| %>
            <div class="input-group">
              <%= f.input_field :name_or_slug_or_description_cont, label: 'Search', class: 'form-control border-white border-top-none', type: :search %>
              <div class="input-group-append">
                <%= f.button :submit, class: 'btn-primary' %>
              </div>
            </div>
          <% end %>
        </div>

        <div class="mb-2">
          <%== pagy_bootstrap_combo_nav_js(@pagy) %>
        </div>
      </div>
    </div>

    <div class="col-12">
      <%= card_row do %>
        <% @channels.each do |channel| %>
          <%= render channel %>
        <% end %>
      <% end %>
    </div>
  </div>

  <br>

  <%#= link_to 'New Channel', new_channel_path %>
</div>

app/views/channels/new.html.erb
<h1>New Channel</h1>

<%= render 'form', channel: @channel %>

<%= link_to 'Back', channels_path %>

app/views/channels/show.html.erb
<%= content_for :head do %>
  <meta property="og:image" content="<%= @channel.image %>">
  <meta name="description" content="<%= @channel.description %>">
<% end %>

<div class="container-fluid">
  <div class="row my-3">
    <div class="col">
      <div class="overflow-hidden align-text-bottom">
        <%= logo_tag @channel, width: "100px" %>
        <div class="float-left ml-3" style="width: calc(100% - 120px); max-width: 60em">
          <h1 class="h3"><%= link_to @channel.name, @channel %></h1>
          <% if @channel.description.present? %>
            <%= simple_format markdown.render(@channel.description).html_safe %>
          <% end %>
        </div>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="col">
      
      <% @sources.each do |source| %>
        <%= link_to I18n.t(source.kind), source.url, class: "btn btn-sm mb-1 btn-#{ source.kind }", target: :blank %>
      <% end %>

      <% @socials.each do |social| %>
        <%= link_to I18n.t(social.kind), social.url, class: "btn btn-sm mb-1 btn-#{ social.kind }", target: :blank %>
      <% end %>
      
      <% @supports.each do |support| %>
        <%= link_to I18n.t(support.kind), support.url, class: "btn btn-sm mb-1 btn-#{ support.kind }", target: :blank %>
      <% end %>
    </div>
  </div>

  <div class="row my-2">
    <div class="col">
      <div class="d-block d-md-flex justify-content-between">
        <h2 class="mr-auto"><%=  I18n.t(:videos) %></h2>

        <div class="">
          <%== pagy_bootstrap_combo_nav_js(@pagy) %>
        </div>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="col">

      <%= card_row do %>
        <% @videos.each do |video| %>
          <%= render video %>
        <% end %>
      <% end %>

      <% if Rails.env.development? %>
        <%= link_to 'Edit', edit_channel_path(@channel) %> |
        <%= link_to 'Sync', sync_channel_path(@channel) %>
      <% end %>
    </div>
  </div>
</div>