config/routes.rb
# For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

Rails.application.routes.draw do
  root 'pages#home'
  get 'about', to: 'pages#about'
  get 'privacy', to: 'pages#privacy'
  get 'process', to: 'pages#process'

  LINKS.each do |path, url|
    get path.to_s.gsub("_","/"), to: redirect(url)
  end

  REDIRECTS.each do |from, to|
    get from, to: redirect(to)
    get "#{from}/*video", to: redirect("#{to}/%{video}"), constraints: { video: /.*/ }
  end

  resources :channels, only: [:index, :new, :create]
  resources :videos, only: [:index, :new, :create]

  resources :channels, path: '/', except: [:index, :new, :create] do
    member do
      get :sync, :edit # fixes the video path taking over
    end
    resources :videos, path: '/', except: [:index, :new, :create] do
      member do
        get :sync
      end
    end
  end
end

app/views/partials/_beta.html.erb
<div class="alert alert-warning mb-0 text-center mt-2 rounded-0" role="alert">
  <p class="my-0">
    We're still getting content imported into the site, contact <a href="https://twitter.com/DirkKellyCom/status/1287046786184409088" target="_blank"><%= LINKS[:dirkkellycom] %></a> if you’re missing.
  </p>
  <p class="my-0">
    We're also looking for help further developing <%= link_to I18n.t(:breadtubetv), gitlab_breadtubetv_path %> and getting the word out about <%= link_to I18n.t(:breadtubetv_peertube), LINKS[:peertube] %>.
  </p>
</div>

app/views/partials/_foot.html.erb
<%= javascript_pack_tag 'application' %>
<%= javascript_pack_tag 'pagy' %>

app/views/partials/_footer.html.erb
<div id="footer" class="container-fluid mt-4">
  <div class="row">
    <div class="col-12 col-md">
      <h3><%= I18n.t(:content) %></h3>

      <ul class="list-unstyled">
        <li><%= link_to I18n.t(:videos), videos_path %></li>
        <li><%= link_to I18n.t(:channels), channels_path %></li>
      </ul>
    </div>
    <div class="col-12 col-md">
      <h3><%= I18n.t(:about) %></h3>

      <ul class="list-unstyled">
        <li><%= link_to I18n.t(:whats_breadtubetv), about_path %></li>
        <li><%= link_to I18n.t(:hows_breadtubetv_work), process_path %></li>
        <li><%= link_to I18n.t(:privacy_policy), privacy_path %></li>
      </ul>
    </div>
    <div class="col-12 col-md">
      <h3><%= I18n.t(:community) %></h3>

      <ul class="list-unstyled">
        <!--li><%= link_to I18n.t(:guide), '#' %></li>
        <li><%= link_to I18n.t(:creators), '#' %></li-->
        <li><%= link_to I18n.t(:report_issue), "#{LINKS[:gitlab_issues]}?issue[title]=Report '#{ full_page_title }'", taget: "_blank" %></li>
        <li><%= link_to I18n.t(:view_source_code), gitlab_breadtubetv_path, target: "_blank" %></li>
        <li><%= link_to I18n.t(:developers_discord), discord_developers_path, target: "_blank" %></li>
        <li><%= link_to I18n.t(:contact_us), LINKS[:dirkkellycom], target: "_blank" %></li>
      </ul>
    </div>
    <div class="col-12 col-md">
      <h3><%= I18n.t(:find_us_on) %></h3>

      <ul class="list-unstyled">
        <li><%= link_to I18n.t(:youtube), youtube_path, target: "_blank" %></li>
        <li><%= link_to I18n.t(:peertube), peertube_path, target: "_blank" %></li>
        <li><%= link_to I18n.t(:reddit), reddit_path, target: "_blank" %></li>
        <li><%= link_to I18n.t(:twitter), twitter_path, target: "_blank" %></li>
        <li><%= link_to I18n.t(:facebook), facebook_path, target: "_blank" %></li>
        <li><%= link_to I18n.t(:discord), discord_path, target: "_blank" %></li>
      </ul>
    </div>
  </div>
</div>

app/views/partials/_head.html.erb
<title><%= full_page_title %></title>
<%= csrf_meta_tags %>
<%= csp_meta_tag %>

<link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png">
<link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png">
<link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png">
<link rel="manifest" href="/site.webmanifest">
<link rel="mask-icon" href="/safari-pinned-tab.svg" color="#d23e72">
<meta name="msapplication-TileColor" content="#d23e72">
<meta name="theme-color" content="#ffffff">

<meta name="viewport" content="width=device-width, initial-scale=1">

<%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
<script async defer data-domain="breadtube.tv" src="https://stats.breadtube.tv/js/index.js"></script>

<link href="<%= videos_url(format: :xml) %>" rel="alternate" type="application/rss+xml" title="BreadTube.tv: Videos Feed" />

<%= yield :head %>

app/views/partials/_navbar.html.erb
<nav class="navbar navbar-expand-sm navbar-dark bg-dark fixed-top">
  <a class="navbar-brand font-weight-bold mr-auto mr-sm-3" href="/">
    <%= image_tag "/logo.png", width: "24 ", height: "24", class: "d-inline-block align-top" %>
    <%= I18n.t(:breadtubetv) %>
  </a>
  <ul class="navbar-nav mr-right d-block d-sm-none">
    <li class="nav-item">
      <%= 
        link_to LINKS[:peertube_upload], target: "_blank", class: "nav-link border rounded p-1 px-3 m-1 bg-peertube border-peertube font-weight-bold", title: I18n.t(:upload) do
          icon('fas', 'upload') 
        end
      %>
    </li>
  </ul>
  <button class="navbar-toggler mr-right" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item <%= 'active' if current_class?(:videos) %>">
        <%= link_to I18n.t(:videos), videos_path, class: "nav-link" %>
      </li>
      <li class="nav-item <%= 'active' if current_class?(:channels) %>">
        <%= link_to I18n.t(:channels), channels_path, class: "nav-link" %>
      </li>
    </ul>
    <ul class="navbar-nav mr-right d-none d-sm-block">
      <li class="nav-item">
        <%= 
          link_to LINKS[:peertube_upload], target: "_blank", class: "nav-link border rounded p-1 px-3 m-1 bg-peertube border-peertube", title: I18n.t(:upload) do
            icon('fas', 'upload') + " " + I18n.t(:upload)
          end
        %>
      </li>
    </ul>
  </div>
</nav>